server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/hongDou
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
    password:
api:
  ip: https://api.oioweb.cn/api/ip/ipaddress?ip=
service:
  user:
    endpoint: discovery:///user.service
mq:
  url: "amqp://root:123456@localhost:5672/host1"
  # 是否开启处理评论信息
  open: true
  exchange:
    - "comment_exchange"
  queue:
    - "comment_queue"
    - "reward_queue"