server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/hongDou
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
    password:
# 配置黑白名单, 白名单不需要传递Token,黑名单特殊接口需要传递Token
path:
  # 配置白名单 不需要传递token接口
  white:
    - "/api/login"
    - "/api/register"
    - "/api/admin"
    - "/api/updatePassword"
    - "/api/upload"
mq:
  url: "amqp://root:123456@localhost:5672/hongDou"
  # 是否开启处理评论信息
  open: true
  exchange:
    - "gateway_exchange"
  queue:
    - "comment_queue" # 评论队列
    - "reward_queue" # 回复队列
    - "email_queue" #邮件队列