version: '3.0'
services:
  web:
    image: blog:v1
    container_name: hongDou_blog
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - consul
  nginx:
    image: nginx
    container_name: front_nginx
    volumes:
      - "./show:/usr/local/blog/show"
      - "./manager:/usr/local/blog/manager"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8030:8030"
      - "8033:8033"
    depends_on:
      - web
  mysql:
    image: mysql:5.7
    container_name: hongDou_mysql
    ports:
      - "23306:3306"
    environment:
      - "MYSQL_DATABASE=hongDou"
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - "./hongDou.sql:/docker-entrypoint-initdb.d/hongDou.sql"
  redis:
    image: redis:5.0.14
    container_name: hongDou_redis
    ports:
      - "26379:6379"
    command:
      - "redis-server --requirepass 123456"
  consul:
    image: consul:1.7.3
    container_name: hongDou_consul
    ports:
      - "8500:8500"
    command:
      - "consul agent -dev -client=0.0.0.0"
