server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
    password:
upload:
  # 上传路径
  path: E:\HongDou-Go-Blog\kratos-blog\pkg\upload\file
  # 代理域名
  domain: http://localhost:8080/util/img
  # 最大内存
  maxsize: 3 MB
  # Bing 每日随机图片获取接口
  uri: "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1"
# 配置黑白名单, 白名单不需要传递Token,黑名单特殊接口需要传递Token
path:
  # 配置白名单 不需要传递token接口
  white:
    - "/util/upload"
    - "/util/getBingPhoto"
    - "/api/login"
    - "/api/register"
    - "/api/admin"
    - "/api/updatePassword"
  # 配置黑名单 Get请求但需要传递token接口
  black:
    - "/api/searchBlog"
# 设置允许访问路由
domain:
  # 允许访问源
  origin:
    - "http://localhost:8033"
    - "http://localhost:8030"
  # 是否开启过滤器
  open: false